### ISSUE TITLE
Docker error on Windows. packet_cafe_admin can't bind to port 5001

### ISSUE THREAD

**Issue by sawft99** [IQTLabs/packet_cafe#489]
I've pulled the docker image onto a windows machine. Several other containers start without issue but the admin portion reports the following error: The main webpage does come up however. Windows 10 2009 and newest version of docker installed on windows.

(HTTP code 500) server error - Ports are not available: listen tcp 0.0.0.0:5001: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

**Comment by cglewis** [comment]
Hi @sawft99,

I haven't tried running Packet Café on Windows, but this issue seems related and might help with that issue: https://github.com/docker/for-win/issues/3171

**Comment by sawft99** [comment]
> Hi @sawft99,
> 
> I haven't tried running Packet Café on Windows, but this issue seems related and might help with that issue: [docker/for-win#3171](https://github.com/docker/for-win/issues/3171)

Reserving the port seemed to resolve that particular issue. Thanks.
